language : python

python:
  - 3.5
install:
  - pip install python-coveralls
  - pip install coverage
  - pip install python3-matplotlib
script:
  - coverage run test_rpn.py
after_success:
  - coveralls
